### PR TITLE
Region monitoring

### PR DESCRIPTION
**Pull request by simonox**
Added region monitoring to nativescript-plugin.

### CODE REVIEW

**Comment by demetrio812** [comment]
Thanks @simonox I'll review it ASAP and merge it

**Comment by simonox** [comment]
Already added some improvements at the end of last week.

**Comment by demetrio812** [comment]
Thanks, did you test the use case when you close the app and then move the phone near a monitored iBeacon? Does it wake up the app?

In some experiments I've done some months ago I had to create a custom AppDelegate in order to support it...

Let me know...

Thanks,
Dem

**Comment by simonox** [comment]
It wakes up iOS. On Android it does not _start_ an app. If the app is not in the background anymore, nothing happens.

**Comment by demetrio812** [comment]
Thanks, I've just published it!

**Pull request merged**
